export const productsData = [
  {
    id: 1,
    title: "سرم روشن‌کننده ویتامین C",
    brand: "DIOR",
    price: 4900000,
    src: "/images/body.jpg",
    category: "مراقبت پوست",
    rating: 4.8,
    inStock: true,
    colors: ["#F3E5AB", "#FFD700"],
    date: "2024-05-10",
  },
  {
    id: 2,
    title: "رژ لب مایع مات",
    brand: "CHANEL",
    price: 3100000,
    src: "/images/p6.png",
    category: "آرایشی",
    rating: 4.9,
    inStock: true,
    colors: ["#800020", "#C71585"],
    date: "2024-06-01",
  },
  {
    id: 3,
    title: "ادو پرفیوم جادور",
    brand: "DIOR",
    price: 8700000,
    src: "/images/dior.jpg",
    category: "عطر و ادکلن",
    rating: 5.0,
    inStock: false,
    colors: ["#10c026", "#C31a25"],
    date: "2024-01-15",
  },
  {
    id: 4,
    title: "کرم پودر فلوئیدی",
    brand: "GIVENCHY",
    price: 4550000,
    src: "/images/p4.png",
    category: "آرایشی",
    rating: 4.7,
    inStock: true,
    colors: ["#F5DEB3", "#DEB887"],
    date: "2024-05-25",
  },
];
export const availableColors = [
  "#F3E5AB",
  "#FFD700",
  "#800020",
  "#C71585",
  "#F5DEB3",
  "#DEB887",
];

export const Filters = [
  { id: "newest", label: "جدیدترین" },
  { id: "expensive", label: "گران‌ترین" },
  { id: "cheapest", label: "ارزان‌ترین" },
];
